In [1]:
import pandas as pd
import numpy as np
from functions import *
from pathlib import Path

In [2]:
# autoreload
%reload_ext autoreload
%autoreload 2

In [3]:
#########################################
# Full data pipeline for the ML project #
#########################################

# Step 1: Import the data from an external source; this uses the function in data.py called load_raw_data

rides = load_raw_data(year=2022, months=None)
rides

file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.
file is already downloaded and in the data directory.

            pickup_datetime  pickup_location_id
0       2022-01-01 00:35:40                 142
1       2022-01-01 00:33:43                 236
2       2022-01-01 00:53:21                 166
3       2022-01-01 00:25:21                 114
4       2022-01-01 00:36:48                  68
...                     ...                 ...
3399544 2022-12-31 23:46:00                  16
3399545 2022-12-31 23:13:24                  75
3399546 2022-12-31 23:00:49                 168
3399547 2022-12-31 23:02:50                 238
3399548 2022-12-31 23:00:15                  85

[39654634 rows x 2 columns]

In [4]:
# Step 2: Create the time series data from the cleaned raw data

ts_data = transform_raw_data_into_ts_data(rides=rides)
print(ts_data)

100%|██████████| 262/262 [00:01<00:00, 220.24it/s]

                pickup_hour  rides  pickup_location_id
0       2022-01-01 00:00:00     11                   4
1       2022-01-01 01:00:00     15                   4
2       2022-01-01 02:00:00     26                   4
3       2022-01-01 03:00:00      8                   4
4       2022-01-01 04:00:00      9                   4
...                     ...    ...                 ...
2295115 2022-12-31 19:00:00      0                 199
2295116 2022-12-31 20:00:00      0                 199
2295117 2022-12-31 21:00:00      0                 199
2295118 2022-12-31 22:00:00      0                 199
2295119 2022-12-31 23:00:00      0                 199

[2295120 rows x 3 columns]

In [5]:
features, targets = transform_ts_data_into_features_and_target(ts_data=ts_data,
                                                               input_seq_len=24*28*1, # one month
                                                               step_size=24) 

print(f'{features.shape=}')
print(f'{targets.shape=}')

  0%|          | 0/262 [00:00<?, ?it/s]

100%|██████████| 262/262 [00:12<00:00, 21.31it/s]

features.shape=(88294, 674)
targets.shape=(88294,)

In [6]:
tabular_data = features
tabular_data['target_rides_next_hour'] = targets
tabular_data.to_parquet(CLEANED_DATA_DIR / 'tabular_data.parquet')

In [15]:
pd.set_option('display.max_rows', 10)
tabular_data

,rides_previous_672_hour,rides_previous_671_hour,rides_previous_670_hour,rides_previous_669_hour,rides_previous_668_hour,rides_previous_667_hour,rides_previous_666_hour,rides_previous_665_hour,rides_previous_664_hour,rides_previous_663_hour,...,rides_previous_7_hour,rides_previous_6_hour,rides_previous_5_hour,rides_previous_4_hour,rides_previous_3_hour,rides_previous_2_hour,rides_previous_1_hour,pickup_hour,pickup_location_id,target_rides_next_hour
0,11.0,15.0,26.0,8.0,9.0,7.0,3.0,1.0,0.0,3.0,...,11.0,7.0,4.0,3.0,4.0,9.0,19.0,2022-01-29,4,17.0
1,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,5.0,4.0,10.0,7.0,5.0,9.0,10.0,2022-01-30,4,9.0
2,0.0,1.0,0.0,0.0,1.0,1.0,1.0,3.0,2.0,3.0,...,8.0,7.0,8.0,5.0,5.0,10.0,0.0,2022-01-31,4,3.0
3,1.0,1.0,0.0,0.0,0.0,3.0,2.0,3.0,4.0,5.0,...,3.0,16.0,7.0,1.0,0.0,1.0,3.0,2022-02-01,4,3.0
4,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,1.0,2.0,...,3.0,8.0,3.0,0.0,4.0,4.0,3.0,2022-02-02,4,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88289,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-12-27,199,0.0
88290,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-12-28,199,0.0
88291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-12-29,199,0.0
88292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-12-30,199,0.0
88293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2022-12-31,199,0.0